### PR TITLE
arpack: bump for openblas

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by dpo** [comment]
@sjackman Any idea why https://github.com/LinuxbrewTestBot/homebrew-num/releases isn't showing a new release here? The bottles don't appear on Bintray. I tried http://linuxbrew.sh/linuxbrew-lambda/ but haven't had any success.

**Comment by sjackman** [comment]
The first thing to check is that the bottles are on CircleCI. Click on the `collect-bottles` CircleCI step.
Then select the `Artifacts` tab. We have two bottles, so that's good.
https://circleci.com/gh/brewsci/homebrew-num/285#artifacts/containers/0
Down at the bottom select `Uploading artifacts`. Check that the size of the bottles are less than ~100-200 MB. Too big overwhelms AWS Lambda. We're good in this case.

https://circleci.com/api/v1.1/project/github/brewsci/homebrew-num/latest/artifacts?branch=pull/29
returns
`{ "message" : "Build not found" }`
That's the root problem. I'm not sure why though. That seems to me to a bug over at CircleCI.

Try
```sh
git rebase origin/master && git commit --amend && git push dpo bump-arpack --force
```
and cross your fingers that CircleCI works this time around. If not, we'll have to contact CircleCI support.

**Comment by dpo** [comment]
No luck unfortunately. Any ideas?

**Comment by sjackman** [comment]
You could try opening a new PR with a new branch name, as a last stab. If that doesn't work, you'll need to contact CircleCI support. They're been quite responsive for me. Point them to this URL: https://circleci.com/api/v1.1/project/github/brewsci/homebrew-num/latest/artifacts?branch=pull/29

**Comment by dpo** [comment]
It worked by pushing to a different branch! Hopefully, that was just a temporary glitch. Thanks @sjackman !

**Comment by sjackman** [comment]
I'm glad to hear that worked! When in doubt, hit it again, harder. =)

**Pull request closed without merging**
