### PR TITLE
Switch to GitHub Actions

### PR DESCRIPTION
**Pull request by SeekingMeaning**
Based on `homebrew-bio`

Requires a new `develop` branch that should be set as the default branch instead of `master`.
The default branch can be changed in **Settings &rarr; Branches**: https://github.com/brewsci/homebrew-num/settings/branches

### CODE REVIEW

**Comment by sjackman** [comment]
> I'm not sure which exact scopes should be enabled, but I enabled repo, admin:repo_hook, and workflow for my personal tap (@sjackman could you verify this?)

Only `public_repo` is needed. I'd suggest keeping the permissions as slim as possible. You can add more permissions later as needed, even without needing to recreate the token.

**Comment by sjackman** [comment]
I believe that we could configure the Brewsci organization to use the same `HOMEBREW_GITHUB_API_TOKEN` and `HOMEBREW_BINTRAY_KEY` configuration and token for all of its repos. I haven't yet looked into this GitHub feature.

**Comment by SeekingMeaning** [comment]
> I believe that we could configure the Brewsci organization to use the same `HOMEBREW_GITHUB_API_TOKEN` and `HOMEBREW_BINTRAY_KEY` configuration and token for all of its repos.

Yeah I'm fairly certain that'll work. Do happen to have the `HOMEBREW_GITHUB_API_TOKEN` stored somewhere? You can't access existing tokens at https://github.com/settings/tokens

**Comment by dpo** [comment]
Hm. I can't seem to access settings for this repo any more, and so can't set `develop` as the default branch.

@sjackman Any ideas?

@SeekingMeaning is this PR still up to date? Sorry it took so long to get to it.

**Comment by SeekingMeaning** [comment]
> @SeekingMeaning is this PR still up to date? Sorry it took so long to get to it.

I'm leaning towards not having the `develop` branch as Homebrew doesn't clone the `master` branch by default anymore and instead clones whichever branch is set as the default on GitHub

**Comment by dpo** [comment]
Thank you!

**Comment by SeekingMeaning** [comment]
Wait I wasn't finished

**Comment by dpo** [comment]
Oops. Sorry.

**Comment by dpo** [comment]
Should I revert or do you want to open a new PR?

**Pull request merged**
