### PR TITLE
brewsci-arpack: delete formula

### PR DESCRIPTION
**Pull request by SeekingMeaning**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dpo** [comment]
Here I think we also need to pass `-fallow-argument-mismatch` to gfortran when building with gcc ≥ 10.

**Comment by dpo** [comment]
Maybe this formula is obsolete actually. It's in core (where they applied the same fix: https://github.com/Homebrew/homebrew-core/blob/master/Formula/arpack.rb#L40) and core also builds it with OpenBLAS.

**Comment by SeekingMeaning** [comment]
What should we do? Deprecate the formula? Disable it? Or perhaps delete it?

**Comment by dpo** [comment]
I deleted brewsci-scalapack for the same reason. This repo started because core wasn't building against OpenBLAS by default. It seems that now they are...

**Comment by dpo** [comment]
It doesn't seem brewsci-arpack or brewsci-ipopt are dependencies of anything.

**Pull request merged**
