### PR TITLE
arpack: new formula

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by sjackman** [comment]
Sigh. This time CircleCI built no bottles.
See https://circleci.com/gh/brewsci/homebrew-num/38
and https://circleci.com/gh/brewsci/homebrew-num/40#artifacts/containers/0

I'm not sure why. I know I'm sounding like a broken record, but can you try `git commit --amend && git push --force` again?

**Comment by dpo** [comment]
When I first opened this PR, I saw again Github report that the bottling job finished before the other two. I don't know if it's a glitch in the communication with CircleCI, but it's consistent with the fact that no bottles were built.

**Comment by sjackman** [comment]
I think it's a communication glitch between CircleCI and GitHub. CircleCI reports that `build-linux` and `build-macos` both completed 15 min ago, and `collect-bottles` completed 12 min ago.
https://circleci.com/gh/brewsci/homebrew-num/tree/pull/4

**Comment by sjackman** [comment]
Still no luck. I'll try troubleshooting interactively on CircleCI using ssh.

**Comment by dpo** [comment]
Sorry it's so much trouble.

**Comment by sjackman** [comment]
Here's the environment from CircleCI:
```sh
CI=true
CIRCLECI=true
CIRCLE_BRANCH=pull/4
CIRCLE_BUILD_NUM=44
CIRCLE_BUILD_URL=https://circleci.com/gh/brewsci/homebrew-num/44
CIRCLE_COMPARE_URL=
CIRCLE_INTERNAL_CONFIG=/.circleci-runner-config.json
CIRCLE_INTERNAL_SCRATCH=/tmp/circleci-256108529
CIRCLE_INTERNAL_TASK_DATA=/.circleci-task-data
CIRCLE_JOB=build-linux
CIRCLE_NODE_INDEX=0
CIRCLE_NODE_TOTAL=1
CIRCLE_PREVIOUS_BUILD_NUM=41
CIRCLE_PROJECT_REPONAME=homebrew-num
CIRCLE_PROJECT_USERNAME=brewsci
CIRCLE_PR_NUMBER=4
CIRCLE_PR_REPONAME=homebrew-num
CIRCLE_PR_USERNAME=dpo
CIRCLE_REPOSITORY_URL=https://github.com/brewsci/homebrew-num
CIRCLE_SHA1=c94a9c417281817e7a53b831a7c88aa80d7ac81f
CIRCLE_STAGE=build-linux
CIRCLE_USERNAME=sjackman
CIRCLE_WORKFLOW_UPSTREAM_JOB_IDS=
CIRCLE_WORKING_DIRECTORY=~/project
```
The critical environment variable `CI_PULL_REQUEST` is missing.

**Comment by sjackman** [comment]
I've enabled…
```
Pass secrets to builds from forked pull requests

Run builds for fork pull request changes with this project's configuration, environment variables, and secrets.
```
https://circleci.com/gh/brewsci/homebrew-num/edit#advanced-settings

I'm cautiously hopeful.

@dpo Please `git commit --amend && git push --force` (I hope you're not counting)

**Comment by dpo** [comment]
No worries. Here we go for another round. Thanks for investigating!

**Comment by sjackman** [comment]
```
ARGV: --bintray-org=linuxbrew --root-url=https://linuxbrew.bintray.com/bottles-num --git-name=LinuxbrewTestBot --git-email=testbot@linuxbrew.sh --verbose --ci-auto --no-pull --ci-master --cleanup --test-default-formula --junit --fast
```
https://circleci.com/gh/brewsci/homebrew-num/46

It's still confused. `--ci-master` should be `--ci-pr`. It's doing that because the environment variable `CI_PULL_REQUEST` is not set. Can you try opening a new PR, once again? If that doesn't work, I'll contact CircleCI support again. Sorry that getting this going has been so much hassle.

**Comment by dpo** [comment]
I'm just looking through the settings. Don't we want to turn "Only build pull requests" on?

**Comment by sjackman** [comment]
> Don't we want to turn "Only build pull requests" on?

We build bottles on pull requests. On the push to `master`, we download the bottles and confirm that they exist (are published on Bintray).

**Pull request closed without merging**
