### PR TITLE
Bump scalapack openblas 2

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by dpo** [comment]
@sjackman I'm extremely confused. PR #40 built correctly but
- didn't result in a new release on https://github.com/LinuxbrewTestBot/homebrew-num/releases
- **did** result in the artifacts being uploaded to Bintray (???).

So I couldn't `brewsci-pull` it. I closed it and opened this new PR. And to my surprise:
- there's a new release labeled after PR #40 (not this one)
- artifacts are nevertheless uploaded to Bintray.

Something seems to be a bit off.

**Comment by sjackman** [comment]
After the PR successfully builds, it can take up to five minutes for the tagged release to appear. That's my best guess as to what happened.

**Comment by dpo** [comment]
Unless it took a lot longer than that, I don't know what happened.

**Comment by sjackman** [comment]
Did you merge PR 40?

**Comment by sjackman** [comment]
How did you close this issue?

**Comment by dpo** [comment]
I fixed up the commit message.

**Pull request closed without merging**
