### PR TITLE
brewsci-hwloc 1.11.9 (new formula)

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by dpo** [comment]
```
Error: 2 problems in 1 formula detected
  * Formulae should not require patches to build. Patches should be submitted and accepted upstream first.
  * Formulae should not require patches to build. Patches should be submitted and accepted upstream first.
```

**Comment by sjackman** [comment]
You can use `inreplace` if a one-line fix is sufficient.

**Comment by sjackman** [comment]
If not, if you can get it to build without the patch, you can open the new-formula PR without the patch, and then add the patch in a revision.

**Comment by dpo** [comment]
This formula is no longer necessary. StarPU (#26) builds against the latest `hwloc`.

**Pull request closed without merging**
