### PR TITLE
tetgen 1.5.1 (migrated from homebrew-science)

### PR DESCRIPTION
**Pull request by zbeekman**
- Better tests added
 - Transition to using CMake build system
 - Install manual & headers in addition to library and binary

### CODE REVIEW

**Comment by zbeekman** [comment]
@sjackman I'm trying out a fix for CircleCI... but perhaps you already have this done on homebrew-bio or homebrew-base?

Also, what do you think about this package's potential for being added to homebrew-core?

**Comment by sjackman** [comment]
The fix to CircleCI looks good. It looks the same as in Brewsci/bio.

**Comment by sjackman** [comment]
> Also, what do you think about this package's potential for being added to homebrew-core?

I have no strong opinion. If you'd like to support both macOS and Linux, that's easier in a third party tap. If you prefer to use OpenBLAS and MPICH (rather than Accelerate and OpenMPI), use brewsci/num.

**Comment by sjackman** [comment]
The bottles transferred successfully to Bintray, so AWS Lambda bot is working.
https://github.com/LinuxbrewTestBot/homebrew-num/releases/tag/pr-43

**Comment by zbeekman** [comment]
Anything fancy one needs to do to merge this?

**Comment by sjackman** [comment]
```sh
alias brewsci-pull='HOMEBREW_BOTTLE_DOMAIN=https://linuxbrew.bintray.com brew pull --bottle --bintray-org=linuxbrew --test-bot-user=LinuxbrewTestBot'
brewsci-pull https://github.com/brewsci/homebrew-num/pull/43
```

**Comment by zbeekman** [comment]
Do I need to be in the linuxbrew bintray org?

**Comment by sjackman** [comment]
Yes. I've invited you just now!

**Comment by dpo** [comment]
I created a new PR with the CI update only (see #45) because I need it for #44. You can update this when #45 is merged. Thanks!

**Comment by zbeekman** [comment]
@sjackman do I need to be on linux for this to work as anticipated?
> ```shell
> alias brewsci-pull='HOMEBREW_BOTTLE_DOMAIN=https://linuxbrew.bintray.com brew pull --bottle --bintray-org=linuxbrew --test-bot-user=LinuxbrewTestBot'
> brewsci-pull https://github.com/brewsci/homebrew-num/pull/43
> ```

On macOS I'm getting: 

```


curl: (22) The requested URL returned error: 404 Not Found
Error: Failure while executing; `/usr/bin/curl -q --show-error --user-agent Homebrew/2.0.2-78-g59aac33\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.3\)\ curl/7.54.0 --fail --progress-bar --location --remote-time --continue-at 0 --output /Users/ibeekman/Library/Caches/Homebrew/brewsci:master...pr-43.patch https://github.com/LinuxbrewTestBot/homebrew-num/compare/brewsci:master...pr-43.patch` exited with 22. Here's the output:

curl: (22) The requested URL returned error: 404 Not Found
```

EDIT: Then I am returned a shell on the `pull-bottle-43` branch, and `master` has one commit like this:

```
 commit 3fa05d7a0e50a2e7f08015946888a8f3b14a5df6 (HEAD -> master)
 Author: Izaak Beekman <zbeekman@gmail.com>
 Date:   Fri Feb 22 12:33:32 2019 -0500

     tetgen 1.5.1 (migrated from homebrew-science)

      - Better tests added
      - Transition to using CMake build system
      - Install manual & headers in addition to library and binary

     Closes #43.

     Signed-off-by: Izaak Beekman <zbeekman@gmail.com>
```

**Comment by sjackman** [comment]
`brewsci-pull` works on either Linux or macOS.

Here are the steps in troubleshooting:

1. Check that CircleCI built a bottle. Select `ci/circleci: collect-bottles` then `Artifacts`
2. Select `Uploading artifacts` and verify that the bottles are smaller than 100 MB
3. Go to https://github.com/LinuxbrewTestBot/homebrew-num/releases and look for your PR. https://github.com/LinuxbrewTestBot/homebrew-num/releases/tag/pr-43 is 404, so your bottles did not transfer to Bintray and Github.
4. Go to https://bintray.com/linuxbrew/bottles-num and check for existing published bottles for this exact same version (from an aborted `brew pull --bottle` that was not pushed to `master`)

If there are bottles on CircleCI but not on Bintray/GitHub, then AWS Lambda bot is to blame.
1. Go to http://linuxbrew.sh/linuxbrew-lambda/
2. Select the tap
3. Enter the PR number
4. Select *Trigger*
5. Wait exactly five minutes (no less, no need for more)
6. Go to https://github.com/LinuxbrewTestBot/homebrew-num/releases and look for your bottle

If that does not work, mention me, and I'll look into it.

**Comment by zbeekman** [comment]
@sjackman 
Still no joy. The url `https://p4142ivuwk.execute-api.us-west-2.amazonaws.com/prod/ci-upload/github.com/brewsci/homebrew-num/pull/43` returns:

```json
{"message": "Endpoint request timed out"}
```

I wonder if the late bintray add, the cherry pick from this PR in #44 for #45, or my forced push to this branch caused the issues with aws/bottling. I wonder if I just close this PR and open a new one if that will do the trick. I'll wait until I hear back before running any further experiments.

**Comment by dpo** [comment]
@zbeekman In my experience, deleting existing bottles from Bintray sometimes helps.

**Comment by sjackman** [comment]
> I wonder if I just close this PR and open a new one if that will do the trick.

You can try `git commit --amend && git push --force` first.

**Comment by sjackman** [comment]
📰 **This just in!** Your last attempt worked. https://github.com/LinuxbrewTestBot/homebrew-num/releases/tag/pr-43

**Comment by zbeekman** [comment]
@sjackman great! It still returned the time-out json, but I guess deleting the bottle resolved and trying again that part of the issue. Now, in my local working copy I have 1 commit ahead of master, but I don't have the commit (f1f2a5427c105fbda725e54d5cf08afd7a7491f6) adding the bottle block. How do you suggest I proceed? I could just cherry-pick f1f2a5427c105fbda725e54d5cf08afd7a7491f6 from LinuxbrewTestBot/homebrew-num@pr-43, or if I run `brewsci-pull` again will it be smart enough to pick-up where it left off? Or run `brewsci-pull` but without the `--bottle` argument to `brew pull`?

**Comment by sjackman** [comment]
> It still returned the time-out json

That's unfortunately the normal behaviour. AWS API Gateway times out after 30 seconds, even though AWS Lambda keeps running for five minutes. It's not great, but it hasn't been a priority to fix.

**Comment by sjackman** [comment]
> Now, in my local working copy I have 1 commit ahead of master, but I don't have the commit ([f1f2a54](https://github.com/brewsci/homebrew-num/commit/f1f2a5427c105fbda725e54d5cf08afd7a7491f6)) adding the bottle block. How do you suggest I proceed?

```sh
git checkout master
git fetch origin
git reset --hard origin/master
brewsci-pull https://github.com/brewsci/homebrew-num/pull/43
```

**Pull request closed without merging**
