### PR TITLE
brewsci-mumps: revision for dependent libraries

### PR DESCRIPTION
**Pull request by dpo**
fix links to dependent libraries in shared objects

### CODE REVIEW

**Comment by dpo** [comment]
I'm getting this unexpected message on CircleCI/Linux:
```
mpirun has detected an attempt to run as root.

Running as root is *strongly* discouraged as any mistake (e.g., in
defining TMPDIR) or bug can result in catastrophic damage to the OS
file system, leaving your system in an unusable state.

We strongly suggest that you run mpirun as a non-root user.
```
@sjackman Are we technically logged in as "root" on the Linux VMs?

**Comment by sjackman** [comment]
> Are we technically logged in as "root" on the Linux VMs?

The default user in the Docker container. That's a fairly recent change. If that above MPI message is a warning, I suggest simply ignoring it. If it's an error, we can discuss solutions.

**Comment by dpo** [comment]
Yes it's an error. No Linux bottles were produced as a result. I tried setting environment variables (in the CircleCI settings) as they suggest to allow running mpirun as root, but it didn't seem to have any effect.

**Comment by sjackman** [comment]
`brew install` expunges the environment by default. You would need to modify the environment within the formula with `ENV["FOO"] = "BAR"`. That'd be the easiest fix if it works.

**Comment by dpo** [comment]
Thanks @sjackman. That worked.

**Pull request closed without merging**
