### PR TITLE
arpack: new formula

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by dpo** [comment]
I know this sounds weird but the `collect-bottles` finished first again. There was sufficient time for me to click on it and notice that it had indeed completed over at CircleCI...

screen shot 2018-10-12 at 14 04 24

**Comment by sjackman** [comment]
Still says `--ci-master` meaning no `CI_PULL_REQUEST` environment variable. I'll reply to the open CircleCI ticket.

**Comment by sjackman** [comment]
Sorry for the hold up, Dominique. CircleCI support believe we've run into a bug in CircleCI, and they're looking into it.

**Comment by dpo** [comment]
No worries. Thanks for being in touch with them!

**Comment by sjackman** [comment]
@dpo I see now why `collect-bottles` is already ✅ while `build-linux` and `build-macos` are 💛 . A rebuild of the workflow triggers a rebuild of `build-linux` and `build-macos` first, which updates their status to 💛 , but a rebuild of `collect-bottles` has not yet been triggered, so it's previous status of ✅ is still displayed.

**Comment by sjackman** [comment]
CircleCI support wrote…

> Hi Shaun,
The issue should now be resolved. Please let us know if you continue to experience any issues.
Happy building!

Here's hoping!

**Comment by sjackman** [comment]
CircleCI on macOS
```
==> brew install --only-dependencies --include-test brewsci/num/brewsci-arpack
==> FAILED
Error: Calling `or_later` bottles is deprecated! Use bottles without `or_later` (or_later is implied now) instead.
```
https://circleci.com/gh/brewsci/homebrew-num/62

**Comment by sjackman** [comment]
Opened PR https://github.com/brewsci/homebrew-num/pull/7 to remove the `--or-later` issue.

**Comment by sjackman** [comment]
I've rebased this PR onto `origin/master`.

**Comment by sjackman** [comment]
Success! See https://bintray.com/linuxbrew/bottles-num/brewsci-arpack#files

**Comment by dpo** [comment]
Yahoo! Many thanks Shaun! I'll now submit more PRs.

**Comment by sjackman** [comment]
I use this alias to pull the bottles:
```sh
alias brewsci-pull='HOMEBREW_BOTTLE_DOMAIN=https://linuxbrew.bintray.com brew pull --bottle --bintray-org=linuxbrew --test-bot-user=LinuxbrewTestBot'
brewsci-pull https://github.com/brewsci/homebrew-num/pull/6
```
Not all of it's necessary if you're working on Linux with Linuxbrew/brew. It's needed for pulling the bottles on macOS with Homebrew/brew.

**Comment by dpo** [comment]
Very sweet! Thank you! I managed to pull a bottle, which was uploaded to Bintray. What do you then use to merge the PR?

**Comment by dpo** [comment]
Ah, nevermind, I got it.

**Comment by sjackman** [comment]
Just a heads up that the `cellar …` is not always determined correctly. It's an outstanding bug.
`arpack` was detected as non-relocatable, and `metis` was detected as `cellar :any_skip_relocation`. Some formula that should be `cellar :any` are detected as `cellar :any_skip_relocation`, which is fine for Linux (which treats them both the same) but breaks pouring bottles on macOS. If you see that, you can change it. The bottle is fine.

**Pull request closed without merging**
