### PR TITLE
suite-sparse: bump for openblas

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by dpo** [comment]
@sjackman Could you remind me what the procedure is in a case like this one? `suite-sparse` fails because `brew test-bot` tests `ceres-solver`, which depends on `suite-sparse`, but hasn't been updated yet and fails. Do you update two formulae in the same PR?

**Comment by sjackman** [comment]
> Do you update two formulae in the same PR?

Yes, you bump the revision for both in the same PR.

**Comment by sjackman** [comment]
I like your issue labels! I know GitHub has a feature to transfer issue labels between repos, or to set one for the whole organization. I'd like to use your labels for all of Brewsci.

**Comment by dpo** [comment]
Go for it! I hope that gets me some help credits ;-). I'm a bit stuck in the other PRs where bottles don't appear to be uploaded.

**Comment by sjackman** [comment]
> Go for it! I hope that gets me some help credits ;-)

I don't have time right now, but I'll put it on my wish list! If you can figure out how to do it and have the necessary permissions, go right ahead. You can start with https://github.com/brewsci/homebrew-base

> I'm a bit stuck in the other PRs where bottles don't appear to be uploaded.

Ping me in an example pull request, and I can look into it.

**Comment by sjackman** [comment]
Do you know about http://linuxbrew.sh/linuxbrew-lambda/ to re-transfer stuck bottles from CircleCI to Bintray? Also the unpublished bottles time out and are deleted from Bintray after one week.

**Pull request closed without merging**
