### PR TITLE
arpack: new formula

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by dpo** [comment]
`collect-bottles` finished before the builds themselves?!

**Comment by sjackman** [comment]
Still broken:
https://circleci.com/api/v1.1/project/github/brewsci/homebrew-num/latest/artifacts?branch=pull/3
Can you try the ol' `git commit --amend && git push --force` again?

**Comment by sjackman** [comment]
> collect-bottles finished before the builds themselves?!

From here it looks like the jobs were run in the correct order:
https://circleci.com/gh/brewsci/homebrew-num/tree/brewsci-arpack
https://circleci.com/workflow-run/71b6a682-84b2-4580-9cc0-54d976675709

**Comment by sjackman** [comment]
The issue is with CircleCI's API not returning the expected value.
If we can't figure it out, we'll need to open a support ticket with CircleCI.
https://circleci.com/api/v1.1/project/github/brewsci/homebrew-num/latest/artifacts?branch=pull/3 is returning `"message" : "Build not found"`
It should return the same result as https://circleci.com/api/v1.1/project/github/brewsci/homebrew-num/31/artifacts
As far as I can tell, that's a bug over at CircleCI.
Curiously, this returns the right value:
https://circleci.com/api/v1.1/project/github/brewsci/homebrew-num/latest/artifacts
Here's the relevant API documentation: https://circleci.com/docs/api/v1-reference/#build-artifacts-latest

Where's an example of what the API ought to return:
https://circleci.com/api/v1.1/project/github/brewsci/homebrew-bio/latest/artifacts?branch=pull/482

**Comment by sjackman** [comment]
This option was disabled in CircleCI (the default). Perhaps that's related.
```
Build forked pull requests
Run builds for pull requests from forks. CircleCI will automatically update the commit status shown on GitHub's pull request page.
```
https://circleci.com/gh/brewsci/homebrew-num/edit#advanced-settings

CircleCI was building the fork pull requests anyway, which is odd come to think of it. But perhaps this setting was interfering with the API.

**Comment by sjackman** [comment]
@dpo Can you try `git commit --amend && git push --force again`? Please comment when you have.

**Comment by dpo** [comment]
Done. Thanks.

**Comment by sjackman** [comment]
Nope. Still broken. I'll open a ticket with CircleCI.

**Pull request closed without merging**
