### PR TITLE
arpack: new formula

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by sjackman** [comment]
No luck. I'm contacting CircleCI support.

**Comment by sjackman** [comment]
I've enabled `Only build pull requests`. https://circleci.com/gh/brewsci/homebrew-num/edit#advanced-settings

This article https://support.circleci.com/hc/en-us/articles/360006357533 and CircleCI support say that it should help.
@dpo Can you try `git commit --amend && git push --force` once again?

**Comment by sjackman** [comment]
> Only build pull requests
By default, we will build all the commits for this project. Once turned on, we will only build branches that have associated pull requests open. *Note: For your default branch, we will always build all commits.*

I only just saw this note. I was concerned that enabling this option would prevent `master` from being built. It sounds like that's not the case.

**Comment by sjackman** [comment]
I like the emoji that you added to the issue labels!

**Comment by dpo** [comment]
Thanks! Here we go.

**Comment by dpo** [comment]
Hm. Still no joy?

**Comment by sjackman** [comment]
```
ARGV: --bintray-org=linuxbrew --root-url=https://linuxbrew.bintray.com/bottles-num --git-name=LinuxbrewTestBot --git-email=testbot@linuxbrew.sh --verbose --ci-auto --no-pull --ci-master --cleanup --test-default-formula --junit --fast
```
https://circleci.com/gh/brewsci/homebrew-num/51

It still says `--ci-master` which means the `CI_PULL_REQUEST` environment variable is not being set. It may be because you're using the same branch name `brewsci-arpack ` for each pull request. Try using a new branch name, and open a new pull request.

**Comment by sjackman** [comment]
Superseded by PR #6

**Pull request closed without merging**
