### PR TITLE
arpack: new formula

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by dpo** [comment]
Can't new formulae have a `head` now???

**Comment by sjackman** [comment]
> Can't new formulae have a head now???

`brew audit --new-formula` complains about `head`. You can add it in after the first PR is merged. I'm not a fan of this check either. You could open a PR upstream if you liked to make this check apply only to Homebrew/core (`official_tap?`).

**Comment by sjackman** [comment]
```
./test: error while loading shared libraries: libarpack.so.2: cannot open shared object file: No such file or directory
```
This issue affects testing keg-only formulae. The `def install` block uses Superenv, which adds the necessary `RPATH`. The `test do` block uses Stdenv, which does not set `RPATH` by default. You can add `-Wl,-rpath=#{lib}` to fix this issue.

**Comment by sjackman** [comment]
```
The GitHub credentials in the macOS keychain may be invalid.
```
I can fix this issue.

```
Dependency 'openblas' may be unnecessary as it is provided by macOS; try to build this formula without it.
```
We'll have to figured out how to disable this audit for this tap. Unless you have a need for a `brewsci-openblas` formula.

**Comment by dpo** [comment]
Thanks @sjackman !

> `Dependency 'openblas' may be unnecessary as it is provided by macOS; try to build this formula without it.`

It would be easy to add `brewsci-openblas` here, but it would be quite redundant. I hope there's a way to disable this audit. Accelerate continues to be broken and macOS clearly doesn't provide OpenBLAS.

**Comment by sjackman** [comment]
I've opened PR https://github.com/Homebrew/brew/pull/5067 to disable the `head` check for non-official taps.

**Comment by dpo** [comment]
Should `openblas` be added to [this list](https://github.com/Homebrew/brew/blob/7cb1ceb75618df9936821649d5b38948c51031d6/Library/Homebrew/dev-cmd/audit.rb#L434)?

**Comment by sjackman** [comment]
I've opened PR https://github.com/Linuxbrew/brew/pull/862 to permit `openblas`.

**Comment by sjackman** [comment]
I've merged PR https://github.com/Linuxbrew/brew/pull/862 to Linuxbrew/brew, but now that I think about it, we're probably Homebrew/brew on macOS, so merging that PR won't help immediately. We'll need to get it merged upstream at Homebrew/brew.

`openblas` is keg-only. Do the libraries provided by `openblas` conflict with those provided by Accelerate?

**Comment by sjackman** [comment]
`nwchem` appears to be the only formula in core with a hard dependency on `openblas`.

**Comment by dpo** [comment]
> openblas is keg-only. Do the libraries provided by openblas conflict with those provided by Accelerate?

No; the openblas library is named `libopenblas`. The Accelerate libraries are named `libblas` and `liblapack`. They provide the same functionality, except that they are not tuned in the same way (their performance differs), and Accelerate is currently incomplete and buggy.

**Comment by sjackman** [comment]
If there's no conflicting libraries nor headers, then perhaps `openblas` could be made non-keg only in Homebrew/core, which would resolve this issue. Would you like to open such a PR?

**Comment by dpo** [comment]
Ah, sorry, there are no conflicting libraries, but there are conflicting headers, though those supplied with Accelerate (like `cblas.h`) are located in `/Library` and/or `/System/Library` and are part of the Accelerate and vecLib frameworks.

**Comment by sjackman** [comment]
Best not to shadow those headers then. Would you like to submit a PR similar to PR https://github.com/Linuxbrew/brew/pull/862 upstream to Homebrew/brew?

**Comment by sjackman** [comment]
It could be conditional on `@official_tap`, so that `openblas` still gives that audit error in `Homebrew/core`, but not in taps like `Brewsci/num`.

**Comment by dpo** [comment]
https://github.com/Homebrew/brew/pull/5072

**Comment by dpo** [comment]
@sjackman Should we also disable the `head` check on Linux?

**Comment by sjackman** [comment]
> @sjackman Should we also disable the head check on Linux?

Yes. I'll do that right after I've merged 1.7.7 into Linuxbrew/brew. See PR https://github.com/Linuxbrew/brew/pull/863

**Comment by sjackman** [comment]
Done. I've merged PR https://github.com/Linuxbrew/brew/pull/864.

**Comment by dpo** [comment]
Thanks @sjackman! It appears to build correctly now. What's the procedure to upload the bottles to Bintray?

**Comment by sjackman** [comment]
I've opened PR https://github.com/Linuxbrew/linuxbrew-lambda/pull/7 to add Brewsci/num to the webservice that transfers bottles from CircleCI to Bintray.

**Comment by sjackman** [comment]
Something is broken over at CircleCI.
https://circleci.com/api/v1.1/project/github/brewsci/homebrew-num/latest/artifacts?branch=pull/2
reports
```
{
  "message" : "Build not found"
}
```
but https://circleci.com/api/v1.1/project/github/brewsci/homebrew-num/19/artifacts is correct.
Try `git commit --amend && git push --force` to trigger a new build at CircleCI.

**Comment by sjackman** [comment]
After the CircleCI build is successful, you should see a new tag named `pr-2` created at
https://github.com/LinuxbrewTestBot/homebrew-num/releases

**Comment by dpo** [comment]
```
webhook returned http status 504, connecting to https://p4142ivuwk.execute-api.us-west-2.amazonaws.com/prod/ci-upload
```

**Comment by sjackman** [comment]
That `status 504` is sadly normal and a red herring. You can ignore it.

The real problem is that this CircleCI API call is not returning the desired result:
https://circleci.com/api/v1.1/project/github/brewsci/homebrew-num/latest/artifacts?branch=pull/2

Even though the bottles are being built fine:
https://circleci.com/gh/brewsci/homebrew-num/25#artifacts/containers/0

Can you try opening a new PR with the same contents as this one?

**Comment by dpo** [comment]
It's in #3.

**Pull request closed without merging**
