### PR TITLE
scalapack, mumps: bump for openblas

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by zbeekman** [comment]
FYI Homebrew-core transitioned to linking against OpenBLAS, and has completely deprecated Accelerate.

I'll try to take a look and see if any formulae here can just be dropped because it's the same in homebrew-core and linuxbrew.

The scalapack patch here references an issue on the CMake bug tracker but from the discussion there it sounds as if this patch should be incorporated upstream in scalapack.

**Comment by zbeekman** [comment]
I've emailed the scalapack development team asking them to patch upstream. I tried to register for the user form but got server side errors. The patch and linux-specific stuff is the only substantive difference from Homebrew-core for scalapack.

I've reported the bug upstream to the scalapack dev team.

@dpo Would it make sense for me to apply the patch on homebrew-core and then we can mark scalapack as migrated to homebrew-core once it's patched there? 

(To reduce your duplication of effort for maintenance.)

**Comment by dpo** [comment]
The main reason left for these formulae to exist is that homebrew/core may not be happy with the default build options. But if you find that core accepts those options, I'm happy to migrate them. Thanks.

**Comment by zbeekman** [comment]
@dpo: How does the lack of the scalapack patch manifest itself? Does it cause a build failure, or just a configuration without a feature? I'm trying to decide if it should be ported to core. I think the answer is probably yes.

I'll try to look at these and then at core where both formulae exist and open PRs to migrate ones that match.

**Comment by dpo** [comment]
@zbeekman I seem to remember it was a build failure, but I admit I haven't tried without the patch lately.

**Pull request closed without merging**
