### PR TITLE
Fix audit errors

### PR DESCRIPTION
**Pull request by SeekingMeaning**

### CODE REVIEW

**Comment by dpo** [comment]
Thanks! Is there a new recommended syntax for the remaining error? If not, can we read from an environment variable that the user will have set?

**Comment by SeekingMeaning** [comment]
> Is there a new recommended syntax for the remaining error?

Not that I'm aware of

> If not, can we read from an environment variable that the user will have set?

We could read an environment variable as long as it has the prefix `HOMEBREW_`, so `HOMEBREW_MATLAB_PATH` would work

**Comment by SeekingMeaning** [comment]
Build fails, but audit no longer prints errors so this should be good to merge

**Comment by dpo** [comment]
Thank you!

**Pull request merged**
